basePath: /api/v1
definitions:
  http_exception.HttpError:
    properties:
      error:
        type: any
      message:
        type: string
      status:
        type: integer
    type: object
  http_exception.HttpSuccess:
    properties:
      current_page:
        type: integer
      data:
        type: any
      limit:
        type: integer
      page:
        type: integer
    type: object
host: localhost:3000
info:
  contact:
    email: develop@acetime.com.br
    name: Acetime Soluções
    url: https://www.acetime.com.br
  title: Acetime Business API Documentation
  version: 1.0.0
paths:
  /enterprises:
    get:
      consumes:
      - application/json
      description: Find All Enterprises
      parameters:
      - description: Current page to paginate
        in: query
        name: page
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http_exception.HttpSuccess'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http_exception.HttpError'
      summary: Enterprises
      tags:
      - enterprise
    post:
      consumes:
      - application/json
      description: Create Enterprise
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Create Enterprise
      tags:
      - enterprise
  /enterprises/{id}:
    delete:
      consumes:
      - application/json
      description: Delete Enterprise
      parameters:
      - description: EnterpriseID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Delete Enterprise
      tags:
      - enterprise
    get:
      consumes:
      - application/json
      description: Find All Enterprises
      parameters:
      - description: Enterprise ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Enterprise by id
      tags:
      - enterprise
    put:
      consumes:
      - application/json
      description: Update Enterprise
      parameters:
      - description: EnterpriseID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Update Enterprise
      tags:
      - enterprise
swagger: "2.0"
