version: '2.7'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: acetimesolucoes
    networks:
      - external
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db
    
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: acetimesolucoes
  #     ME_CONFIG_MONGODB_URL: mongodb://root:acetimesolucoes@mongo:27017

  # api:
  #   build:
  #     context: .
  #   container_name: acetimesolucoes-bscrm-api
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - .:/opt/acetimesolucoes
  #   working_dir: /opt/acetimesolucoes

volumes:
  mongodbdata:
    driver: local

networks:
  external:
    driver: bridge