FROM golang:1.17 AS builder

WORKDIR /workspace

COPY go.mod /workspace/
COPY go.sum /workspace/
COPY apps/api /workspace/
COPY apps/api/main.go /workspace/

RUN go build -o /workspace/api/main.go

FROM gcr.io/distroless/base-debian10 as final

WORKDIR /

COPY --from=builder /api /api

ENV PORT=3000
ENV HOST=0.0.0.0

EXPOSE 3000

USER nonroot:nonroot

CMD [ "/api" ]


