# FROM golang:1.18 AS builder
FROM golang:1.20-alpine

WORKDIR /workspace

COPY ./apps/api ./
COPY ./libs ./libs
COPY ./tools ./tools

RUN go mod download
RUN go install github.com/swaggo/swag/cmd/swag@latest

# RUN swag init

# RUN go build -o ./main.go
RUN go build

# FROM gcr.io/distroless/base-debian10 as final

# WORKDIR /

# COPY --from=builder /workspace/api /api

ENV PORT=3000
ENV HOST=0.0.0.0

EXPOSE 3000

# RUN go run main.go

# USER nonroot:nonroot

CMD [ "./marketbooster" ]